#
# PostgreSQL. Versions 8.2 and up are supported.
#

common: &common
  adapter: postgresql
  # username: median
  # password: h4a2z3

development:
  <<: *common
  database: median_dev
  # log levels: debug{5..1}, notice (default), warning, error, fatal, panic
  #min_messages: warning

test:
  <<: *common
  username: median
  database: median_test

production:
  <<: *common
  database: median_prod
