#
# PostgreSQL. Versions 8.2 and up are supported.
#

common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: median
  password: h4a2z3

development:
  <<: *common
  database: median_dev
  # Minimum log levels, in increasing order: debug{5..1}, notice (default), warning, error, fatal, panic
  #min_messages: warning

test:
  <<: *common
  database: median_test

production:
  <<: *common
  database: median_prod
